// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTime.Shared.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyTime.Shared.Migrations
{
    [DbContext(typeof(MyTimeDbContext))]
    partial class MyTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyTime.Shared.Model.Punch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PunchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PunchedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PunchedUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Punches");
                });
#pragma warning restore 612, 618
        }
    }
}
